project:
  type: book  
  output-dir: docs
  post-render:
    - ./compile-slides

book:
  title: "Evaluation of Bridges Collapsing in Omaha, Nebraska"
  author: "Max Buettenback"
  page-footer:
    left: "Copyright 2026, Max Buettenback"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



