project:
  type: book  
  output-dir: docs
  post-render:
    - ./compile-slides

book:
  title: "Evaluation of <scenario>"
  author: "Author Name"
  page-footer:
    left: "Copyright 2025, Author Name"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - Conclusion.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



